name: Publish Docker Image to GHCR

on:
  push:
    tags:
      - go-hello-*  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log Tag
      run: |
        echo "Triggered by tag: ${{ github.ref_name }}"

    # Step 2: Log in to GHCR
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/go-hello:${{ github.ref_name }} /src/go/hello

    # Step 4: Push the Docker image to GHCR
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository }}/myapp:latest
