name: Go Release
on:
  workflow_dispatch:  # Allow manual runs
  push:
    branches:
      - main
    paths:
      - 'src/go/**/*.go'
      - 'src/go/**/Dockerfile'
      - 'src/go/**/.releaserc'
jobs:
  release:
    permissions:
      contents: write
      issues: write
      packages: write # To push the Docker image to GHCR
      id-token: write # Required for OIDC authentication
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run tests
        run: go test ./...
        working-directory: src/go/hello

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install plugins
        run: |
          npm install @semantic-release/exec -D

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release
        run: npx semantic-release
        working-directory: src/go/hello
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Debug
        run: git status
